# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3975be59716f4ee2154d5db36f1a57052e30ce13b8e018b65737590c887559865330a8589ef2717484e7d7674667c45ac4383495c4926c5995729585aa18e56c

test:
  secret_key_base: d94eb1a3a9fff4b9a9575ebb5420bfd594e4a39fe47b1c6264e17cf261843a52406542ca2b5f40eeb4b37500edd8ccd617807fa41bfce981ec475db03f5537b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
